name: Caroline Malcolm
favicon: null
layout_spectrum: 0.039198774844408035
typography_spectrum: 0.11912293964996934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5099251139909029
  lightness: 0.768714337144047
  saturation: 0.7302165837027133
  rhythmicContrast: 0.3297982660587877
purpose: []
